# Generated by Django 5.2.6 on 2025-09-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='客户编号')),
                ('name', models.CharField(max_length=255, verbose_name='客户名称')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户类别:省内/省外')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人手机号')),
                ('logistic', models.CharField(blank=True, max_length=255, null=True, verbose_name='货运部')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='城市')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='街道')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='供应商编号')),
                ('name', models.CharField(max_length=255, verbose_name='供应商名称')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商类别(没有及新增)：织厂/批发商')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人手机号')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商地址')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人邮箱')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'supplier',
            },
        ),
    ]
