# Generated by Django 5.2.6 on 2025-09-19 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_alter_customer_auth_code_alter_supplier_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='供应商编号'),
        ),
    ]
