# Generated by Django 5.2.6 on 2025-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='name',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='系统配置值'),
        ),
        migrations.AlterField(
            model_name='categoryconfig',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='department',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='address',
            field=models.CharField(max_length=500, verbose_name='单据地址'),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='tip',
            field=models.CharField(default='温馨提示：请细查货物，如有质量问题请在七天内提出，一经开剪，恕不退换，谢谢合作。', max_length=500, verbose_name='提示'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='type',
            field=models.CharField(choices=[('product_category', '货物类别：布/纱/书版'), ('unit', '货物单位：米/本/套'), ('version', '版本：W03/W05'), ('settlement_method', '结算方式：现金/月结/微信'), ('logistic', '货运部：顺丰/拼包/申通/圆通'), ('payment_method', '收款方式：现金/微信/支付宝')], max_length=50, verbose_name='系统配置类型'),
        ),
    ]
