# Generated by Django 5.2.6 on 2025-09-19 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_systemconfig_name_systemconfig_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryConfig',
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='type',
            field=models.CharField(choices=[('product_category', '货物类别：布/纱/书版'), ('unit', '货物单位：米/本/套'), ('version', '版本：W03/W05'), ('settlement_method', '结算方式：现金/月结/微信'), ('logistic', '货运部：顺丰/拼包/申通/圆通'), ('payment_method', '收款方式：现金/微信/支付宝'), ('customer', '客户：省内/省外'), ('supplier', '供应商：织厂/批发商')], max_length=50, verbose_name='系统配置类型'),
        ),
    ]
