# Generated by Django 5.2.6 on 2025-09-13 14:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=255, verbose_name='仓库名称')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='负责人')),
                ('manager_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='负责人手机号')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库地址')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='仓库电话')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('ticket_no', models.CharField(max_length=255, verbose_name='票号')),
                ('purchase_date', models.DateField(default=datetime.date.today, verbose_name='进货日期')),
                ('type', models.CharField(choices=[('in', '进货'), ('out', '出货')], default='in', max_length=10, verbose_name='类型')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='经办人')),
                ('settlement_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='结算方式')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.supplier', verbose_name='供应商')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '进货单',
                'verbose_name_plural': '进货单',
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('product_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='货品型号')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='货品名称')),
                ('version', models.CharField(blank=True, max_length=255, null=True, verbose_name='版本：W03/W05')),
                ('spec', models.CharField(blank=True, max_length=255, null=True, verbose_name='规格：2.8米')),
                ('category', models.CharField(blank=True, max_length=255, null=True, verbose_name='货品类别：布/纱/书版')),
                ('unit', models.CharField(blank=True, max_length=255, null=True, verbose_name='单位：米/本/套')),
                ('number', models.IntegerField(verbose_name='原来数量')),
                ('stock_number', models.IntegerField(default=0, verbose_name='库存数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进货单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('is_revoke', models.BooleanField(default=False, verbose_name='是否作废')),
                ('revoke_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='作废原因')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.purchaseorder', verbose_name='进货单: 可以没有进货单')),
            ],
            options={
                'verbose_name': '进货单明细',
                'verbose_name_plural': '进货单明细',
                'db_table': 'purchase_order_line',
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('sale_date', models.DateField(default=datetime.date.today, verbose_name='销售日期')),
                ('no', models.CharField(max_length=255, verbose_name='销售单号: 销202509120001, 可以根据需求量设置长度')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='经办人')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='收款方式')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售单',
                'verbose_name_plural': '销售单',
                'db_table': 'sale_order',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='授权码')),
                ('create_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建用户ID')),
                ('update_user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='更新用户ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='销售单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='折扣')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.saleorder', verbose_name='销售单')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.purchaseorderline', verbose_name='进货单明细')),
            ],
            options={
                'verbose_name': '销售单明细',
                'verbose_name_plural': '销售单明细',
                'db_table': 'sale_order_line',
            },
        ),
    ]
