# Generated by Django 5.2.6 on 2025-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='auth_code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='授权码'),
        ),
    ]
